INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER01', 'iOS', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER01', 'Android', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER01', 'iOS', 'FAIL');

-- 2. wait 10-15 sec INSERT DATA 2 DATA (PROVE HOPPING)
-- Wait about 10-15 seconds manually
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER01', 'iOS', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER01', 'Android', 'FAIL');

-- 3. wait above 30 sec for new window
-- Wait > 30 seconds manually

-- 4. INSERT DATA 4 DATA
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER01', 'iOS', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER01', 'Android', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER01', 'iOS', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER01', 'Android', 'FAIL');

-- 5. SELECT * ALL WINDOW
-- Monitor Tumbling Window (Fixed 30s non-overlapping)
SET 'auto.offset.reset' = 'earliest';
SELECT * FROM MB_LOGIN_EVENTS_STG_TUMBLING_ST_<USER> EMIT CHANGES;

-- Monitor Hopping Window (30s window, hop every 10s)
SET 'auto.offset.reset' = 'earliest';
SELECT * FROM MB_LOGIN_EVENTS_STG_HOPPING_TB_<USER> EMIT CHANGES;

-- Monitor Session Window (Group events with gap < 30s)
SET 'auto.offset.reset' = 'earliest';
SELECT * FROM MB_LOGIN_EVENTS_STG_SESSION_TB_<USER> EMIT CHANGES;
