
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER04', 'iOS', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER04', 'Android', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER04', 'iOS', 'FAIL');

-- 3. wait above 30 sec for new window
-- Wait > 30 seconds manually

-- 4. INSERT DATA 4 DATA
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER04', 'iOS', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER04', 'Android', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER04', 'iOS', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER04', 'Android', 'FAIL');

-- Monitor Tumbling Window
SET 'auto.offset.reset' = 'earliest';
SELECT * FROM MB_LOGIN_EVENTS_STG_TUMBLING_ST_<USER> WHERE USER_ID = 'USER04';

--------------------------------------------------------------------------------------------------------------------------------

INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER02', 'iOS', 'SUCCESS');

-- 2. wait 10-15 sec INSERT DATA 2 DATA (PROVE HOPPING)
-- Wait about 10-15 seconds manually
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER02', 'iOS', 'SUCCESS');

-- 3. wait above 60 sec for new window
-- Wait > 60 seconds manually
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER02', 'iOS', 'SUCCESS');

-- Monitor Hopping Window
SET 'auto.offset.reset' = 'earliest';
SELECT * FROM MB_LOGIN_EVENTS_STG_HOPPING_TB_<USER> WHERE USER_ID = 'USER02';

--------------------------------------------------------------------------------------------------------------------------------

INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER03', 'iOS', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER03', 'Android', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER03', 'iOS', 'FAIL');

-- 3. wait above 30 sec for new window
-- Wait > 30 seconds manually

-- 4. INSERT DATA 4 DATA
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER03', 'iOS', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER03', 'Android', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER03', 'iOS', 'SUCCESS');
INSERT INTO MB_LOGIN_EVENTS_RAW_ST_<USER> (USER_ID, DEVICE_TYPE, LOGIN_STATUS) VALUES ('USER03', 'Android', 'FAIL');

-- Monitor Session Window
SET 'auto.offset.reset' = 'earliest';
SELECT * FROM MB_LOGIN_EVENTS_STG_SESSION_TB_<USER> WHERE USER_ID = 'USER03';