--------------------------------------------------------------------------------------
-- MOCK DATA FOR MAIN PIPELINE (RAW -> STG -> JOIN -> SVC)
-- Stream: BAAC_POC_MFEC_ACCOUNT_ST, BAAC_POC_MFEC_TRANSACTION_ST
--------------------------------------------------------------------------------------

-- 1. Setup Master Data (Account)
-- Notes: ข้อมูลเหล่านี้จะไหลลง BAAC_POC_MFEC_ACCOUNT_TB ด้วย
INSERT INTO BAAC_POC_MFEC_ACCOUNT_ST (STRUCT_KEY, ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_BALANCE, ACCOUNT_TYPE, UPDATE_TS, __OP)
VALUES (STRUCT(ACCOUNT_ID := 'ACC001'), 'ACC001', 'Somchai Jai Dee', 50000.00, 'SAVINGS', FROM_UNIXTIME(UNIX_TIMESTAMP()), 'c');

INSERT INTO BAAC_POC_MFEC_ACCOUNT_ST (STRUCT_KEY, ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_BALANCE, ACCOUNT_TYPE, UPDATE_TS, __OP)
VALUES (STRUCT(ACCOUNT_ID := 'ACC002'), 'ACC002', 'Maneeline Sroy', 12000.50, 'CURRENT', FROM_UNIXTIME(UNIX_TIMESTAMP()), 'c');

INSERT INTO BAAC_POC_MFEC_ACCOUNT_ST (STRUCT_KEY, ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_BALANCE, ACCOUNT_TYPE, UPDATE_TS, __OP)
VALUES (STRUCT(ACCOUNT_ID := 'ACC999'), 'ACC999', 'Test User Gap', 0.00, 'SAVINGS', FROM_UNIXTIME(UNIX_TIMESTAMP()), 'c');


-- 2. Transaction Data (Normal Case) -> Flows to STG10 -> Joins -> SVC
-- Notes: match ACC001, Amount > 0
INSERT INTO BAAC_POC_MFEC_TRANSACTION_ST (STRUCT_KEY, TXN_ID, TXN_CODE, TXN_AMT, TXN_TYPE, ACCOUNT_ID, TXN_AMOUNT, TXN_TS, UPDATE_TS, __OP)
VALUES (STRUCT(TXN_ID := 'TXN1001'), 'TXN1001', 'dep', 5000, 'DEPOSIT', 'ACC001', 5000.00, UNIX_TIMESTAMP(), FROM_UNIXTIME(UNIX_TIMESTAMP()), 'c');

-- 3. Transaction Data (Reject Case) -> Flows to STG10_REJ
-- Notes: Amount < 0 (-500)
INSERT INTO BAAC_POC_MFEC_TRANSACTION_ST (STRUCT_KEY, TXN_ID, TXN_CODE, TXN_AMT, TXN_TYPE, ACCOUNT_ID, TXN_AMOUNT, TXN_TS, UPDATE_TS, __OP)
VALUES (STRUCT(TXN_ID := 'TXN1002'), 'TXN1002', 'wth', -500, 'WITHDRAW', 'ACC001', -500.00, UNIX_TIMESTAMP(), FROM_UNIXTIME(UNIX_TIMESTAMP()), 'c');

-- 4. Transaction Data (Stream-Stream Join Scenario)
-- Notes: ต้องยิงภายใน 30 วินาทีหลังจากยิง Account (หรือยิง Account ซ้ำเพื่อ update time)
-- Step 4.1 Update Account Time
INSERT INTO BAAC_POC_MFEC_ACCOUNT_ST (STRUCT_KEY, ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_BALANCE, ACCOUNT_TYPE, UPDATE_TS, __OP)
VALUES (STRUCT(ACCOUNT_ID := 'ACC002'), 'ACC002', 'Maneeline Sroy', 12000.50, 'CURRENT', FROM_UNIXTIME(UNIX_TIMESTAMP()), 'u');

-- Step 4.2 Insert Transaction immediately match ACC002
INSERT INTO BAAC_POC_MFEC_TRANSACTION_ST (STRUCT_KEY, TXN_ID, TXN_CODE, TXN_AMT, TXN_TYPE, ACCOUNT_ID, TXN_AMOUNT, TXN_TS, UPDATE_TS, __OP)
VALUES (STRUCT(TXN_ID := 'TXN1003'), 'TXN1003', 'xfr', 2000, 'TRANSFER', 'ACC002', 2000.00, UNIX_TIMESTAMP(), FROM_UNIXTIME(UNIX_TIMESTAMP()), 'c');
