SET 'auto.offset.reset' = 'earliest';

---------------------------------------------STREAM----------------------------------------------------

--BAAC_POC_MFEC_ACCOUNT_ST
CREATE STREAM BAAC_POC_MFEC_ACCOUNT_ST (
  STRUCT_KEY STRUCT<ACCOUNT_ID VARCHAR> KEY,
  ACCOUNT_ID VARCHAR,
  ACCOUNT_NAME VARCHAR,
  ACCOUNT_BALANCE DOUBLE,
  ACCOUNT_TYPE VARCHAR,
  UPDATE_TS TIMESTAMP,
  __OP STRING
) WITH (
  KAFKA_TOPIC = 'BAAC_POC_Pipeline_Master_MFEC_ACCOUNT',
  FORMAT = 'AVRO',
  PARTITIONS = 1,
  REPLICAS = 1
);

--BAAC_POC_MFEC_TRANSACTION_ST
CREATE STREAM BAAC_POC_MFEC_TRANSACTION_ST (
  STRUCT_KEY STRUCT<TXN_ID VARCHAR> KEY,
  TXN_ID VARCHAR,
  TXN_CODE VARCHAR,
  TXN_AMT INTEGER,
  TXN_TYPE VARCHAR,
  ACCOUNT_ID VARCHAR,
  TXN_AMOUNT DOUBLE,
  TXN_TS BIGINT,
  UPDATE_TS TIMESTAMP,
  __OP STRING
) WITH (
  KAFKA_TOPIC = 'BAAC_POC_Pipeline_Transaction_MFEC_TRANSACTION',
  FORMAT = 'AVRO',
  PARTITIONS = 1,
  REPLICAS = 1
);

---------------------------------------------TABLE----------------------------------------------------

--BAAC_POC_MFEC_ACCOUNT_TB
CREATE TABLE BAAC_POC_MFEC_ACCOUNT_TB WITH (
  KAFKA_TOPIC = 'BAAC_POC_MFEC_ACCOUNT_TB',
  FORMAT = 'AVRO',
  PARTITIONS = 1,
  REPLICAS = 1
) AS
SELECT 
  STRUCT_KEY AS STRUCT_KEY,
  LATEST_BY_OFFSET(ACCOUNT_ID, FALSE) AS ACCOUNT_ID,
  LATEST_BY_OFFSET(ACCOUNT_NAME, FALSE) AS ACCOUNT_NAME,
  LATEST_BY_OFFSET(ACCOUNT_BALANCE, FALSE) AS ACCOUNT_BALANCE,
  LATEST_BY_OFFSET(ACCOUNT_TYPE, FALSE) AS ACCOUNT_TYPE,
  LATEST_BY_OFFSET(FORMAT_TIMESTAMP(UPDATE_TS, 'yyyy-MM-dd HH:mm:ss.SSS'), FALSE) AS UPDATE_TS
FROM BAAC_POC_MFEC_ACCOUNT_ST
WHERE __OP != 'd'
GROUP BY STRUCT_KEY
EMIT CHANGES;

--BAAC_POC_MFEC_TRANSACTION_TB
CREATE TABLE BAAC_POC_MFEC_TRANSACTION_TB WITH (
  KAFKA_TOPIC = 'BAAC_POC_MFEC_TRANSACTION_TB',
  FORMAT = 'AVRO',
  PARTITIONS = 1,
  REPLICAS = 1
) AS
SELECT 
  STRUCT_KEY AS STRUCT_KEY,
  LATEST_BY_OFFSET(TXN_ID, FALSE) AS TXN_ID,
  LATEST_BY_OFFSET(TXN_CODE, FALSE) AS TXN_CODE,
  LATEST_BY_OFFSET(TXN_AMT, FALSE) AS TXN_AMT,
  LATEST_BY_OFFSET(TXN_TYPE, FALSE) AS TXN_TYPE,
  LATEST_BY_OFFSET(ACCOUNT_ID, FALSE) AS ACCOUNT_ID,
  LATEST_BY_OFFSET(FORMAT_TIMESTAMP(UPDATE_TS, 'yyyy-MM-dd HH:mm:ss.SSS'), FALSE) AS UPDATE_TS
FROM BAAC_POC_MFEC_TRANSACTION_ST
WHERE __OP != 'd'
GROUP BY STRUCT_KEY
EMIT CHANGES;