-----------------------------------------------------------
-- CLEANUP SCRIPT: 01_Ingestion
-- Drop all streams/tables in this pipeline (Reverse Order)
-- NOTE: Does NOT delete Kafka Topics
-----------------------------------------------------------

-- 06 SVC MASKING
DROP STREAM IF EXISTS BAAC_SVC_MASKED_TXN_ST;

-- 05 STREAM JOIN TABLE
DROP STREAM IF EXISTS BAAC_POC_MFEC_ENRICHED_TXN_ST;

-- 04 TABLE JOIN TABLE
DROP TABLE IF EXISTS BAAC_POC_MFEC_ACCOUNT_TRANSACTION_VIEW_TB;
DROP TABLE IF EXISTS BAAC_POC_MFEC_LATEST_TXN_BY_ACC_TB; -- Helper table

-- 03 STREAM JOIN STREAM
DROP STREAM IF EXISTS BAAC_POC_MFEC_TRANSACTION_ACCOUNT_STG20;

-- 02 STG AND REJ
DROP STREAM IF EXISTS BAAC_POC_MFEC_TRANSACTION_STG10_REJ;
DROP STREAM IF EXISTS BAAC_POC_MFEC_TRANSACTION_STG10;

-- 01 RAW
DROP TABLE IF EXISTS BAAC_POC_MFEC_TRANSACTION_TB;
DROP TABLE IF EXISTS BAAC_POC_MFEC_ACCOUNT_TB;
DROP STREAM IF EXISTS BAAC_POC_MFEC_TRANSACTION_ST;
DROP STREAM IF EXISTS BAAC_POC_MFEC_ACCOUNT_ST;
