---------------------------------------------STREAM JOIN STREAM (STG20)----------------------------------------------------
-- 2.1 STREAM JOIN STREAM
-- Join Transaction (Clean Data from STG10) with Account Stream
-- Keyword: WITHIN 30 SECONDS (ต้องระบุ Window เสมอสำหรับ Stream-Stream Join)

CREATE STREAM BAAC_POC_MFEC_TRANSACTION_ACCOUNT_STG20 WITH (
    KAFKA_TOPIC = 'BAAC_POC_MFEC_TRANSACTION_ACCOUNT_STG20', -- เปลี่ยน Topic เป็น STG20
    FORMAT = 'JSON', 
    PARTITIONS = 1, 
    REPLICAS = 1
) AS 
SELECT 
    A.STRUCT_KEY as STRUCT_KEY,
    A.ACCOUNT_ID as ACCOUNT_ID,
    A.ACCOUNT_NAME as ACCOUNT_NAME,
    A.ACCOUNT_BALANCE as ACCOUNT_BALANCE,
    A.ACCOUNT_TYPE as ACCOUNT_TYPE,
    T.TXN_ID as TXN_ID,
    T.TXN_CODE as TXN_CODE,
    T.TXN_AMT as TXN_AMT,
    T.TXN_TYPE as TXN_TYPE,
    T.UPDATE_TS as TRANS_TS,
    A.UPDATE_TS as ACCOUNT_TS,
    FORMAT_TIMESTAMP(FROM_UNIXTIME(UNIX_TIMESTAMP()),'yyyy-MM-dd HH:mm:ss.SSS', 'UTC+7') as KSQLDB_TS
FROM BAAC_POC_MFEC_ACCOUNT_ST A
INNER JOIN BAAC_POC_MFEC_TRANSACTION_STG10 T -- ใช้ STG10 (Clean Data) แทน RAW
WITHIN 30 SECONDS
ON A.STRUCT_KEY = STRUCT(ACCOUNT_ID := T.ACCOUNT_ID) 
EMIT CHANGES;